# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'dht22-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for dht22-iOS
  pod 'CocoaMQTT'
end
